// <auto-generated />
using System;
using CsvItemAdder.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CsvItemAdder.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307070336_AddUploadHistorySupport")]
    partial class AddUploadHistorySupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CsvItemAdder.API.Models.Item", b =>
                {
                    b.Property<string>("LocaCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loca_code");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("item_code");

                    b.Property<string>("Copcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("copcode");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Qty1")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty1");

                    b.Property<decimal>("Qty2")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty2");

                    b.Property<int?>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.HasKey("LocaCode", "ItemCode");

                    b.HasIndex("UploadId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("CsvItemAdder.API.Models.UploadRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuplicateRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SavedRows")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Uploads", (string)null);
                });

            modelBuilder.Entity("CsvItemAdder.API.Models.Item", b =>
                {
                    b.HasOne("CsvItemAdder.API.Models.UploadRecord", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Upload");
                });
#pragma warning restore 612, 618
        }
    }
}
